adb shell setprop log.tag.ByteBufferEncoder VERBOSE 
adb shell setprop log.tag.Downsampler VERBOSE 
adb shell setprop log.tag.ImageHeaderParser VERBOSE 
adb shell setprop log.tag.ViewTarget VERBOSE 
adb shell setprop log.tag.tag VERBOSE 
adb shell setprop log.tag.Request VERBOSE 
adb shell setprop log.tag.RMFragment VERBOSE 
adb shell setprop log.tag.RMRetriever VERBOSE 
adb shell setprop log.tag.SupportRMFragment VERBOSE 
adb shell setprop log.tag.ManifestParser VERBOSE 
adb shell setprop log.tag.FactoryPools VERBOSE 
adb shell setprop log.tag.ContentLengthStream VERBOSE 
adb shell setprop log.tag.TransformationUtils VERBOSE 
adb shell setprop log.tag.BitmapEncoder VERBOSE 
adb shell setprop log.tag.BufferGifDecoder VERBOSE 
adb shell setprop log.tag.GifEncoder VERBOSE 
adb shell setprop log.tag.StreamGifDecoder VERBOSE 
adb shell setprop log.tag.ByteArrayPool VERBOSE 
adb shell setprop log.tag.IntegerArrayPool VERBOSE 
adb shell setprop log.tag.LruBitmapPool VERBOSE 
adb shell setprop log.tag.GlideExecutor VERBOSE 
adb shell setprop log.tag.PreFillRunner VERBOSE 
adb shell setprop log.tag.DiskLruCacheWrapper VERBOSE 
adb shell setprop log.tag.MemorySizeCalculator VERBOSE 
adb shell setprop log.tag.Engine VERBOSE 
adb shell setprop log.tag.DecodeJob VERBOSE 
adb shell setprop log.tag.DecodePath VERBOSE 
adb shell setprop log.tag.SourceGenerator VERBOSE 
adb shell setprop log.tag.ResourceLoader VERBOSE 
adb shell setprop log.tag.FileLoader VERBOSE 
adb shell setprop log.tag.StreamEncoder VERBOSE 
adb shell setprop log.tag.ByteBufferFileLoader VERBOSE 
adb shell setprop log.tag.ThumbStreamOpener VERBOSE 
adb shell setprop log.tag.MediaStoreThumbFetcher VERBOSE 
adb shell setprop log.tag.LocalUriFetcher VERBOSE 
adb shell setprop log.tag.AssetPathFetcher VERBOSE 
adb shell setprop log.tag.HttpUrlFetcher VERBOSE 
adb shell setprop log.tag.Glide VERBOSE 
adb shell setprop log.tag.Volley VERBOSE 
